# Generated by Django 5.1.4 on 2024-12-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('dataset', models.CharField(max_length=50)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
